apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: testserver
build:
  artifacts:
  - image: app
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths: ["k8s/overlays/local"]
