apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    name: sample-pod
spec:
  containers:
  - name: sample-app
    image: gcr.io/matopenkw/manifest:d579460
    ports:
      - containerPort: 8080
