apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deployment
spec:
  selector:
    matchLabels:
      app: dev-app
  template:
    spec:
      containers:
      - name: app
        image: gcr.io/matopenkw/manifest:d579460
        ports:
        - containerPort: 8080

