apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  template:
    spec:
      containers:
      - name: app
        # image: gcr.io/matopenkw/manifest:d579460
        image: app
        ports:
        - containerPort: 8080

